Lix license and add keywords
x3mEr/MMM-MP3Player pull request #1
Opened 2024-02-07 21:10 UTC by KristjanESPERANTO

License should be a valid [SPDX license expression](https://spdx.org/licenses/).

Keywords are used in the [new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on.

2024-03-05 08:36 UTC, KristjanESPERANTO commented
@x3mEr Are you still maintaining this module? 🙂

2024-03-05 17:24 UTC, x3mEr requested changes

2024-03-05 17:24 UTC, x3mEr commented on package.json
> +  "description": "A MagicMirror² module for playing music from folder.",
Contains a special symbol. Please, remove "²".

2024-03-05 17:28 UTC, x3mEr commented
Thank you for your commit!) All good, except this special symbol "²". Don't think it's a good idea to include it into the json file.

2024-03-05 18:35 UTC, KristjanESPERANTO commented
I wonder why you call it special. The ² is not a special character at all. It is simply a squared two and is part of the official spelling of MagicMirror². A normal mathematical character and in ISO-8859-1 since 1998 and also in UTF-8. For the description in package.json it is normal to use UTF-8 characters.

Are you sure I should remove it?

2024-03-06 08:10 UTC, x3mEr commented
It's not in Unicode.

2024-03-06 09:03 UTC, KristjanESPERANTO commented
It's Unicode U+00B2: http://www.unicode-symbol.com/u/00B2.html

2024-03-06 09:39 UTC, x3mEr commented
Oops, was thinking about "ASCII" but has wrote "Unicode".
Nevertheless, you are right: "in json it is normal to use UTF-8 characters".

2024-03-06 09:42 UTC, merged

2024-03-06 10:09 UTC, KristjanESPERANTO commented
No problem 🙂 Fortunately, there are now fewer and fewer systems that are limited to ASCII. Thanks for merging!

2024-03-06 20:33 UTC, KristjanESPERANTO commented
Your module now looks nice on [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) :smiley: